### ISSUE TITLE
NaN existing in 'average_distance' feature

### ISSUE THREAD

**Issue by git-Cade** [KPHippe/ZoomQA#3]
https://github.com/KPHippe/ZoomQA/blob/e6edb8a88f851a0d0811da5270011bfde1c4761f/script/step2_generate_casp_fragment_structures.py#L157

Stems from the first indexes of the 21 element array returned by[ _get_ave(local_contact_info)](https://github.com/KPHippe/ZoomQA/blob/e6edb8a88f851a0d0811da5270011bfde1c4761f/script/assist_generation_scripts/contact_statistics.py#L87)

https://github.com/KPHippe/ZoomQA/blob/e6edb8a88f851a0d0811da5270011bfde1c4761f/script/assist_generation_scripts/contact_statistics.py#L87-L112

When `local_contact_info.items()` is[ sorted and referenced into](https://github.com/KPHippe/ZoomQA/blob/e6edb8a88f851a0d0811da5270011bfde1c4761f/script/assist_generation_scripts/contact_statistics.py#L105) `distance_list`, there exists an edge case where `distance_list` only contains negative values, [which are set to](https://github.com/KPHippe/ZoomQA/blob/e6edb8a88f851a0d0811da5270011bfde1c4761f/script/assist_generation_scripts/contact_statistics.py#L106) `0.0`. <br/><br/>This may lead to `radius_of_gyration` being set to `0.0` through the assignment of `np.max(np.asarray(distance_list))` as it [searches for the max value in the array](https://github.com/KPHippe/ZoomQA/blob/e6edb8a88f851a0d0811da5270011bfde1c4761f/script/assist_generation_scripts/contact_statistics.py#L110), which leads to a division of `0.0` `ave_vector.append(radius_ave/radius_of_gyration)` on the [following line](https://github.com/KPHippe/ZoomQA/blob/e6edb8a88f851a0d0811da5270011bfde1c4761f/script/assist_generation_scripts/contact_statistics.py#L110).<br/>
A NaN is born.

**Comment by KPHippe** [comment]
You did it! Thank you!
